"""Render a HandoffBundle into the portable markdown format (spec v0.1) or JSON,
and read a rendered markdown bundle back into a HandoffBundle for `resume`."""

from __future__ import annotations

import json
import re

from agent_handoff.model import HandoffBundle, Interruption, SessionMeta

BUNDLE_VERSION = "0.2"

# Begin-sentinel for the lossless full-transcript block. It is appended last and
# parsed to end-of-file, so `## ` headings inside verbatim dialogue can never be
# mistaken for bundle section boundaries (which truncated the block before).
_FULL_TRANSCRIPT_SENTINEL = "<!-- agenthandoff:full-transcript (verbatim, oldest first) -->"
_RAW_SENTINEL = "<!-- agenthandoff:raw-archive (byte-faithful vendor storage) -->"

_MARKDOWN_TEMPLATE = """\
# Agent Handoff Bundle

<!-- generated by agenthandoff {version} — human-readable, machine-consumable -->

## Meta

```yaml
bundle_version: "{version}"
cli: {cli}
session_id: "{session_id}"
title: "{title}"
cwd: "{cwd}"
started_at: {started_at}
updated_at: {updated_at}
model: {model}
provider: {provider}
origin: {origin}
parent_session_id: {parent_session_id}
meta_notes: {meta_notes}
tokens_in: {tokens_in}
tokens_out: {tokens_out}
source_path: "{source_path}"
```

## Objective

{objective}

{topics_block}

## Interruption

{interruption}

## State

### Done
{done}

### In progress
{in_progress}

### Blocked / open
{blocked}

## Key user directives

{directives}

## Files touched

{files}

## Next steps

{next_steps}

## Context notes (last assistant conclusions)

{notes}

## Recent context (verbatim tail, oldest first)

{recent}

## Unfinished output (continue from here)

{unfinished}

## Tool usage summary

{tools}
"""


def _yaml_str(v: str | None) -> str:
    return f'"{v}"' if v is not None else 'null'


def _ol(items: list[str], fallback: str = "- (none recorded)") -> str:
    if not items:
        return fallback
    return "\n".join(f"- {i}" for i in items)


def _ul_numbers(items: list[str], fallback: str = "1. (none recorded)") -> str:
    if not items:
        return fallback
    return "\n".join(f"{n}. {i}" for n, i in enumerate(items, 1))


def _render_recent(recent: list[tuple[str, str]]) -> str:
    """`**role** — text` blocks, separated by blank lines (see _parse_recent)."""
    if not recent:
        return "(none recorded)"
    return "\n\n".join(f"**{role}** \u2014 {text}" for role, text in recent)


def _parse_recent(text: str) -> list[tuple[str, str]]:
    out: list[tuple[str, str]] = []
    for block in re.split(r"\n\s*\n", text.strip()):
        m = re.match(r"^\*\*(\w+)\*\* \u2014 (.*)$", block.strip(), re.S)
        if m:
            out.append((m.group(1), m.group(2).strip()))
    return out


def render_markdown(b: HandoffBundle) -> str:
    files = "\n".join(f"- `{p}` (×{n})" for p, n in b.files) or "- (none recorded)"
    tools = (
        "\n".join(f"- {t}: {n} call(s)" for t, n in b.tool_summary)
        or "- (none recorded)"
    )
    it = b.interruption
    it_md = f"- status: {it.kind}"
    if it.kind == "user_pending" and it.pending_user_text:
        it_md += f"\n- pending user message (NOT executed): {it.pending_user_text}"
    elif it.detail:
        it_md += f"\n- detail: {it.detail}"
    topics_block = ""
    if b.topics:
        t_items = "\n".join(f'- "{o}" ({n} user message(s))' for o, n in b.topics)
        topics_block = f"## Topic segments (mixed session)\n\n{t_items}\n"
    out = _MARKDOWN_TEMPLATE.format(
        version=BUNDLE_VERSION,
        cli=b.meta.cli,
        session_id=b.meta.session_id,
        title=b.meta.title.replace('"', "'"),
        cwd=b.meta.cwd,
        started_at=_yaml_str(b.meta.started_at),
        updated_at=_yaml_str(b.meta.updated_at),
        model=_yaml_str(b.meta.model),
        provider=_yaml_str(b.meta.provider),
        origin=_yaml_str(b.meta.origin),
        parent_session_id=_yaml_str(b.meta.parent_session_id),
        meta_notes=_yaml_str("; ".join(b.meta.notes) or None),
        tokens_in=b.meta.tokens_in if b.meta.tokens_in is not None else "null",
        tokens_out=b.meta.tokens_out if b.meta.tokens_out is not None else "null",
        source_path=b.meta.source_path,
        objective=b.objective or "(not captured)",
        topics_block=topics_block,
        interruption=it_md,
        done=_ol(b.done),
        in_progress=_ol(b.in_progress),
        blocked=_ol(b.blocked),
        directives=_ol(b.directives),
        files=files,
        next_steps=_ul_numbers(b.next_steps),
        notes=_ol(b.context_notes),
        recent=_render_recent(b.recent),
        unfinished=b.unfinished or "(none)",
        tools=tools,
    )
    if b.full_transcript:
        payload = json.dumps(
            [{"role": r, "text": t} for r, t in b.full_transcript],
            ensure_ascii=False,
            indent=1,
        )
        out += "\n" + _FULL_TRANSCRIPT_SENTINEL + "\n" + payload + "\n"
    if b.raw_files:
        payload = json.dumps(b.raw_files, ensure_ascii=False, indent=1)
        out += "\n" + _RAW_SENTINEL + "\n" + payload + "\n"
    return out


def render_json(b: HandoffBundle) -> str:
    return json.dumps(b.to_dict(), ensure_ascii=False, indent=2)


# -- markdown → bundle --------------------------------------------------------

_META_KEYS = (
    "cli", "session_id", "title", "cwd", "started_at", "updated_at",
    "model", "tokens_in", "tokens_out", "source_path",
)


def _parse_yaml_block(text: str) -> dict:
    """Minimal yaml subset: `key: value` with quoted strings or bare scalars."""
    out: dict = {}
    for line in text.splitlines():
        m = re.match(r"^\s*([A-Za-z_][\w]*)\s*:\s*(.*?)\s*$", line)
        if not m:
            continue
        key, val = m.group(1), m.group(2)
        if val.startswith('"') and val.endswith('"'):
            val = val[1:-1]
        elif val in ("null", ""):
            val = None
        elif re.fullmatch(r"-?\d+", val):
            val = int(val)
        out[key] = val
    return out


def _section(text: str, name: str) -> str:
    m = re.search(rf"^## {re.escape(name)}\s*$(.*?)(?=^## |\Z)", text, re.M | re.S)
    return m.group(1).strip() if m else ""


def _section_items(text: str, name: str) -> list[str]:
    """Extract list items from a `##` section (used for notes/directives)."""
    items = []
    for line in _section(text, name).splitlines():
        line = line.strip()
        if line.startswith(("- ", "* ")):
            item = line[2:].strip()
            if item and item != "(none recorded)":
                items.append(item)
    return items


def _subsection(text: str, name: str) -> list[str]:
    m = re.search(rf"^### {re.escape(name)}\s*$(.*?)(?=^### |^## |\Z)", text, re.M | re.S)
    if not m:
        return []
    items = []
    for line in m.group(1).splitlines():
        line = line.strip()
        if line.startswith(("- ", "* ")):
            item = line[2:].strip()
            if item and item != "(none recorded)":
                items.append(item)
    return items


def _parse_full_transcript(text: str) -> list[tuple[str, str]]:
    """Verbatim dialogue from the sentinel block, captured to end-of-file.

    The block is JSON (not the `**role** — text` markdown used for the recent
    tail), so blank lines and `## ` headings inside a message can never corrupt
    the round-trip — the full handoff body is genuinely lossless.
    """
    idx = text.rfind(_FULL_TRANSCRIPT_SENTINEL)
    if idx < 0:
        return []
    blob = text[idx + len(_FULL_TRANSCRIPT_SENTINEL):].strip()
    end = blob.rfind(_RAW_SENTINEL)
    if end >= 0:
        blob = blob[:end].strip()
    try:
        rows = json.loads(blob)
    except ValueError:
        return []
    return [(str(r.get("role")), str(r.get("text"))) for r in rows if isinstance(r, dict)]


def _parse_raw_archive(text: str) -> list[dict]:
    """Byte-faithful raw files from the final sentinel block."""
    idx = text.rfind(_RAW_SENTINEL)
    if idx < 0:
        return []
    blob = text[idx + len(_RAW_SENTINEL):].strip()
    try:
        rows = json.loads(blob)
    except ValueError:
        return []
    return [
        r
        for r in rows
        if isinstance(r, dict) and r.get("path") and r.get("text")
    ]


def parse_bundle_markdown(text: str) -> HandoffBundle:
    """Read back a bundle rendered by render_markdown (lossy on tool_summary)."""
    yaml_match = re.search(r"```yaml\n(.*?)```", text, re.S)
    meta_raw = _parse_yaml_block(yaml_match.group(1)) if yaml_match else {}

    # Interruption section: "- status: <kind>" plus optional detail lines.
    it_kind = "clean"
    it_detail = ""
    it_pending = ""
    for line in _section_items(text, "Interruption"):
        if line.startswith("status: "):
            it_kind = line[len("status: "):]
        elif line.startswith("pending user message (NOT executed): "):
            it_pending = line[len("pending user message (NOT executed): "):]
        elif line.startswith("detail: "):
            it_detail = line[len("detail: "):]
    interruption = Interruption(
        kind=it_kind, detail=it_detail, pending_user_text=it_pending
    )
    meta = SessionMeta(
        cli=str(meta_raw.get("cli") or "unknown"),
        session_id=str(meta_raw.get("session_id") or "unknown"),
        title=str(meta_raw.get("title") or "unknown"),
        cwd=str(meta_raw.get("cwd") or ""),
        started_at=meta_raw.get("started_at"),
        updated_at=meta_raw.get("updated_at"),
        model=meta_raw.get("model"),
        tokens_in=meta_raw.get("tokens_in"),
        tokens_out=meta_raw.get("tokens_out"),
        source_path=str(meta_raw.get("source_path") or ""),
        provider=meta_raw.get("provider"),
        origin=meta_raw.get("origin"),
        parent_session_id=meta_raw.get("parent_session_id"),
        notes=[s.strip() for s in str(meta_raw.get("meta_notes") or "").split(";") if s.strip()],
    )

    files: list[tuple[str, int]] = []
    for line in _section(text, "Files touched").splitlines():
        m = re.match(r"^-\s*`(.+?)`\s*\(×(\d+)\)", line.strip())
        if m:
            files.append((m.group(1), int(m.group(2))))

    next_steps: list[str] = []
    for line in _section(text, "Next steps").splitlines():
        m = re.match(r"^\d+\.\s+(.*)$", line.strip())
        if m and m.group(1) != "(none recorded)":
            next_steps.append(m.group(1))

    topics: list[tuple[str, int]] = []
    for line in _section_items(text, "Topic segments (mixed session)"):
        m = re.match(r'^"(.+?)"\s*\((\d+) user message', line)
        if m:
            topics.append((m.group(1), int(m.group(2))))

    return HandoffBundle(
        meta=meta,
        objective=_section(text, "Objective"),
        interruption=interruption,
        topics=topics,
        done=_subsection(text, "Done"),
        in_progress=_subsection(text, "In progress"),
        blocked=_subsection(text, "Blocked / open"),
        directives=_section_items(text, "Key user directives"),
        files=files,
        next_steps=next_steps,
        context_notes=_section_items(text, "Context notes (last assistant conclusions)"),
        recent=_parse_recent(_section(text, "Recent context (verbatim tail, oldest first)")),
        full_transcript=_parse_full_transcript(text),
        raw_files=_parse_raw_archive(text),
        unfinished=_section(text, "Unfinished output (continue from here)"),
    )


def load_bundle(path: str) -> HandoffBundle:
    """Load a bundle from .md or .json."""
    from pathlib import Path

    p = Path(path)
    text = p.read_text(encoding="utf-8", errors="replace")
    if p.suffix == ".json":
        d = json.loads(text)
        m = d.get("meta", {})
        meta = SessionMeta(
            cli=m.get("cli", "unknown"),
            session_id=m.get("session_id", "unknown"),
            title=m.get("title", "unknown"),
            cwd=m.get("cwd", ""),
            started_at=m.get("started_at"),
            updated_at=m.get("updated_at"),
            model=m.get("model"),
            tokens_in=m.get("tokens_in"),
            tokens_out=m.get("tokens_out"),
            source_path=m.get("source_path", ""),
            provider=m.get("provider"),
            origin=m.get("origin"),
            parent_session_id=m.get("parent_session_id"),
            notes=list(m.get("notes", [])),
        )
        state = d.get("state", {})
        it_raw = d.get("interruption", {})
        interruption = Interruption(
            kind=it_raw.get("kind", "clean"),
            detail=it_raw.get("detail", ""),
            pending_user_text=it_raw.get("pending_user_text", ""),
        )
        return HandoffBundle(
            meta=meta,
            objective=d.get("objective", ""),
            interruption=interruption,
            done=state.get("done", []),
            in_progress=state.get("in_progress", []),
            blocked=state.get("blocked", []),
            directives=d.get("directives", []),
            files=[(f["path"], f["hits"]) for f in d.get("files_touched", [])],
            next_steps=d.get("next_steps", []),
            context_notes=d.get("context_notes", []),
            full_transcript=[
                (m["role"], m["text"]) for m in d.get("full_transcript", [])
            ],
            raw_files=list(d.get("raw_files", [])),
        )
    return parse_bundle_markdown(text)
