"""Render a HandoffBundle into the portable markdown format (spec v0.1) or JSON,
and read a rendered markdown bundle back into a HandoffBundle for `resume`."""

from __future__ import annotations

import json
import re

from agent_handoff.model import HandoffBundle, Interruption, SessionMeta

BUNDLE_VERSION = "0.1"

_MARKDOWN_TEMPLATE = """\
# Agent Handoff Bundle

<!-- generated by agenthandoff {version} — human-readable, machine-consumable -->

## Meta

```yaml
bundle_version: "{version}"
cli: {cli}
session_id: "{session_id}"
title: "{title}"
cwd: "{cwd}"
started_at: {started_at}
updated_at: {updated_at}
model: {model}
tokens_in: {tokens_in}
tokens_out: {tokens_out}
source_path: "{source_path}"
```

## Objective

{objective}

## Interruption

{interruption}

## State

### Done
{done}

### In progress
{in_progress}

### Blocked / open
{blocked}

## Key user directives

{directives}

## Files touched

{files}

## Next steps

{next_steps}

## Context notes (last assistant conclusions)

{notes}

## Tool usage summary

{tools}
"""


def _yaml_str(v: str | None) -> str:
    return f'"{v}"' if v is not None else 'null'


def _ol(items: list[str], fallback: str = "- (none recorded)") -> str:
    if not items:
        return fallback
    return "\n".join(f"- {i}" for i in items)


def _ul_numbers(items: list[str], fallback: str = "1. (none recorded)") -> str:
    if not items:
        return fallback
    return "\n".join(f"{n}. {i}" for n, i in enumerate(items, 1))


def render_markdown(b: HandoffBundle) -> str:
    files = "\n".join(f"- `{p}` (×{n})" for p, n in b.files) or "- (none recorded)"
    tools = (
        "\n".join(f"- {t}: {n} call(s)" for t, n in b.tool_summary)
        or "- (none recorded)"
    )
    it = b.interruption
    it_md = f"- status: {it.kind}"
    if it.kind == "user_pending" and it.pending_user_text:
        it_md += f"\n- pending user message (NOT executed): {it.pending_user_text}"
    elif it.detail:
        it_md += f"\n- detail: {it.detail}"
    return _MARKDOWN_TEMPLATE.format(
        version=BUNDLE_VERSION,
        cli=b.meta.cli,
        session_id=b.meta.session_id,
        title=b.meta.title.replace('"', "'"),
        cwd=b.meta.cwd,
        started_at=_yaml_str(b.meta.started_at),
        updated_at=_yaml_str(b.meta.updated_at),
        model=_yaml_str(b.meta.model),
        tokens_in=b.meta.tokens_in if b.meta.tokens_in is not None else "null",
        tokens_out=b.meta.tokens_out if b.meta.tokens_out is not None else "null",
        source_path=b.meta.source_path,
        objective=b.objective or "(not captured)",
        interruption=it_md,
        done=_ol(b.done),
        in_progress=_ol(b.in_progress),
        blocked=_ol(b.blocked),
        directives=_ol(b.directives),
        files=files,
        next_steps=_ul_numbers(b.next_steps),
        notes=_ol(b.context_notes),
        tools=tools,
    )


def render_json(b: HandoffBundle) -> str:
    return json.dumps(b.to_dict(), ensure_ascii=False, indent=2)


# -- markdown → bundle --------------------------------------------------------

_META_KEYS = (
    "cli", "session_id", "title", "cwd", "started_at", "updated_at",
    "model", "tokens_in", "tokens_out", "source_path",
)


def _parse_yaml_block(text: str) -> dict:
    """Minimal yaml subset: `key: value` with quoted strings or bare scalars."""
    out: dict = {}
    for line in text.splitlines():
        m = re.match(r"^\s*([A-Za-z_][\w]*)\s*:\s*(.*?)\s*$", line)
        if not m:
            continue
        key, val = m.group(1), m.group(2)
        if val.startswith('"') and val.endswith('"'):
            val = val[1:-1]
        elif val in ("null", ""):
            val = None
        elif re.fullmatch(r"-?\d+", val):
            val = int(val)
        out[key] = val
    return out


def _section(text: str, name: str) -> str:
    m = re.search(rf"^## {re.escape(name)}\s*$(.*?)(?=^## |\Z)", text, re.M | re.S)
    return m.group(1).strip() if m else ""


def _section_items(text: str, name: str) -> list[str]:
    """Extract list items from a `##` section (used for notes/directives)."""
    items = []
    for line in _section(text, name).splitlines():
        line = line.strip()
        if line.startswith(("- ", "* ")):
            item = line[2:].strip()
            if item and item != "(none recorded)":
                items.append(item)
    return items


def _subsection(text: str, name: str) -> list[str]:
    m = re.search(rf"^### {re.escape(name)}\s*$(.*?)(?=^### |^## |\Z)", text, re.M | re.S)
    if not m:
        return []
    items = []
    for line in m.group(1).splitlines():
        line = line.strip()
        if line.startswith(("- ", "* ")):
            item = line[2:].strip()
            if item and item != "(none recorded)":
                items.append(item)
    return items


def parse_bundle_markdown(text: str) -> HandoffBundle:
    """Read back a bundle rendered by render_markdown (lossy on tool_summary)."""
    yaml_match = re.search(r"```yaml\n(.*?)```", text, re.S)
    meta_raw = _parse_yaml_block(yaml_match.group(1)) if yaml_match else {}

    # Interruption section: "- status: <kind>" plus optional detail lines.
    it_kind = "clean"
    it_detail = ""
    it_pending = ""
    for line in _section_items(text, "Interruption"):
        if line.startswith("status: "):
            it_kind = line[len("status: "):]
        elif line.startswith("pending user message (NOT executed): "):
            it_pending = line[len("pending user message (NOT executed): "):]
        elif line.startswith("detail: "):
            it_detail = line[len("detail: "):]
    interruption = Interruption(
        kind=it_kind, detail=it_detail, pending_user_text=it_pending
    )
    meta = SessionMeta(
        cli=str(meta_raw.get("cli") or "unknown"),
        session_id=str(meta_raw.get("session_id") or "unknown"),
        title=str(meta_raw.get("title") or "unknown"),
        cwd=str(meta_raw.get("cwd") or ""),
        started_at=meta_raw.get("started_at"),
        updated_at=meta_raw.get("updated_at"),
        model=meta_raw.get("model"),
        tokens_in=meta_raw.get("tokens_in"),
        tokens_out=meta_raw.get("tokens_out"),
        source_path=str(meta_raw.get("source_path") or ""),
    )

    files: list[tuple[str, int]] = []
    for line in _section(text, "Files touched").splitlines():
        m = re.match(r"^-\s*`(.+?)`\s*\(×(\d+)\)", line.strip())
        if m:
            files.append((m.group(1), int(m.group(2))))

    next_steps: list[str] = []
    for line in _section(text, "Next steps").splitlines():
        m = re.match(r"^\d+\.\s+(.*)$", line.strip())
        if m and m.group(1) != "(none recorded)":
            next_steps.append(m.group(1))

    return HandoffBundle(
        meta=meta,
        objective=_section(text, "Objective"),
        interruption=interruption,
        done=_subsection(text, "Done"),
        in_progress=_subsection(text, "In progress"),
        blocked=_subsection(text, "Blocked / open"),
        directives=_section_items(text, "Key user directives"),
        files=files,
        next_steps=next_steps,
        context_notes=_section_items(text, "Context notes (last assistant conclusions)"),
    )


def load_bundle(path: str) -> HandoffBundle:
    """Load a bundle from .md or .json."""
    from pathlib import Path

    p = Path(path)
    text = p.read_text(encoding="utf-8", errors="replace")
    if p.suffix == ".json":
        d = json.loads(text)
        m = d.get("meta", {})
        meta = SessionMeta(
            cli=m.get("cli", "unknown"),
            session_id=m.get("session_id", "unknown"),
            title=m.get("title", "unknown"),
            cwd=m.get("cwd", ""),
            started_at=m.get("started_at"),
            updated_at=m.get("updated_at"),
            model=m.get("model"),
            tokens_in=m.get("tokens_in"),
            tokens_out=m.get("tokens_out"),
            source_path=m.get("source_path", ""),
        )
        state = d.get("state", {})
        it_raw = d.get("interruption", {})
        interruption = Interruption(
            kind=it_raw.get("kind", "clean"),
            detail=it_raw.get("detail", ""),
            pending_user_text=it_raw.get("pending_user_text", ""),
        )
        return HandoffBundle(
            meta=meta,
            objective=d.get("objective", ""),
            interruption=interruption,
            done=state.get("done", []),
            in_progress=state.get("in_progress", []),
            blocked=state.get("blocked", []),
            directives=d.get("directives", []),
            files=[(f["path"], f["hits"]) for f in d.get("files_touched", [])],
            next_steps=d.get("next_steps", []),
            context_notes=d.get("context_notes", []),
        )
    return parse_bundle_markdown(text)
